"""
Automated Report Builder for SPT Analysis.
Generates HTML reports summarizing analysis results.
"""

import os
import json
import datetime
import numpy as np
import pandas as pd
try:
    from jinja2 import Environment, BaseLoader
except ImportError:
    Environment = None

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>SPT Analysis Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1, h2 { color: #2c3e50; }
        .section { margin-bottom: 30px; border-bottom: 1px solid #eee; padding-bottom: 20px; }
        .stats-table { border-collapse: collapse; width: 100%; }
        .stats-table th, .stats-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .stats-table th { background-color: #f2f2f2; }
        .model-card { background: #f9f9f9; padding: 15px; margin: 10px 0; border-radius: 5px; }
        .best-model { border-left: 5px solid #27ae60; }
    </style>
</head>
<body>
    <h1>SPT Analysis Report</h1>
    <p>Generated on: {{ date }}</p>
    
    <div class="section">
        <h2>Experimental Settings</h2>
        <ul>
            <li>Pixel Size: {{ pixel_size }} um</li>
            <li>Frame Interval: {{ frame_interval }} s</li>
            <li>Number of Tracks: {{ num_tracks }}</li>
        </ul>
    </div>

    <div class="section">
        <h2>Model Comparison</h2>
        <p>Best fitting model: <strong>{{ best_model }}</strong></p>
        
        <table class="stats-table">
            <tr>
                <th>Model</th>
                <th>AIC</th>
                <th>R-squared</th>
                <th>Parameters</th>
            </tr>
            {% for model_name, result in model_fits.items() %}
            <tr class="{% if model_name == best_model %}best-model-row{% endif %}">
                <td>{{ model_name }}</td>
                <td>{{ "%.2f"|format(result.aic) }}</td>
                <td>{{ "%.4f"|format(result.r_squared) }}</td>
                <td>
                    {% for k, v in result.parameters.items() %}
                        {{ k }}: {{ "%.4e"|format(v) }}<br>
                    {% endfor %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <div class="section">
        <h2>Detailed Model Results</h2>
        {% for model_name, result in model_fits.items() %}
        <div class="model-card {% if model_name == best_model %}best-model{% endif %}">
            <h3>{{ model_name }}</h3>
            {% if result.success %}
                <p><strong>AIC:</strong> {{ "%.2f"|format(result.aic) }} | <strong>BIC:</strong> {{ "%.2f"|format(result.bic) }}</p>
                <p><strong>Parameters:</strong></p>
                <ul>
                {% for k, v in result.parameters.items() %}
                    <li>{{ k }} = {{ "%.4e"|format(v) }}</li>
                {% endfor %}
                </ul>
            {% else %}
                <p style="color: red;">Fit Failed: {{ result.error }}</p>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    
    <div class="section">
        <h2>Notes</h2>
        <p>This report was automatically generated by the SPT2025B analysis pipeline.</p>
    </div>
</body>
</html>
"""

class ReportBuilder:
    def __init__(self, output_dir="reports"):
        self.output_dir = output_dir
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
            
    def generate_html_report(self, analysis_results: dict, filename="report.html"):
        if Environment is None:
            print("Jinja2 not installed. Cannot generate HTML report.")
            return
            
        env = Environment(loader=BaseLoader(), autoescape=True)
        template = env.from_string(HTML_TEMPLATE)
        
        # Prepare context
        context = {
            'date': datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            'pixel_size': analysis_results.get('pixel_size', 'N/A'),
            'frame_interval': analysis_results.get('frame_interval', 'N/A'),
            'num_tracks': analysis_results.get('num_tracks', 'N/A'),
            'best_model': analysis_results.get('best_model', 'Unknown'),
            'model_fits': analysis_results.get('model_fits', {})
        }
        
        html_content = template.render(context)
        
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, 'w') as f:
            f.write(html_content)
            
        return filepath

    def save_results_json(self, analysis_results: dict, filename="results.json"):
        # Convert numpy types to python types for JSON serialization
        def default(o):
            if isinstance(o, np.integer): return int(o)
            if isinstance(o, np.floating): return float(o)
            if isinstance(o, np.ndarray): return o.tolist()
            return str(o)
            
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, 'w') as f:
            json.dump(analysis_results, f, default=default, indent=4)
            
        return filepath
